import { computeSha256Digest, type Sha256Digest } from "../../foundation/crypto/sha256.js";
import { encodeUtf8 } from "../../foundation/text/utf8.js";
import {
  createTodoCollectionSnapshot,
  isTodoCollectionStatusActive,
  type TodoCollectionSnapshot,
} from "./todo-collection.js";
import { TODO_BOARD_PROJECTION_REF } from "./todo-paths.js";

/**
 * Wakeflow Governance / TODO：JSON 权威集合的 Markdown 投影。
 *
 * 投影只使用已经验证的 Intake 和 State 快照，不展示已撤回或已归档条目。文件内容携带
 * 集合基准摘要，缺失或损坏时可以重建；任何状态转换都不能反向读取投影作为权威。
 */

const TODO_BOARD_PROJECTION_KIND =
  "wakeflow-todo-board-projection" as const;
const TODO_BOARD_PROJECTION_VERSION = 1 as const;

export interface TodoBoardProjection {
  readonly artifactKind: typeof TODO_BOARD_PROJECTION_KIND;
  readonly schemaVersion: typeof TODO_BOARD_PROJECTION_VERSION;
  readonly resourcePath: typeof TODO_BOARD_PROJECTION_REF;
  readonly basisDigest: Sha256Digest;
  readonly sourceDigest: Sha256Digest;
  readonly rowCount: number;
  readonly content: string;
}

const TODO_PROJECTION_COLUMNS = Object.freeze([
  "ID",
  "Status",
  "Demand Type",
  "Priority",
  "Origin Window",
  "Controller Window",
  "Summary",
  "Intake Rationale",
  "Dependency / Trigger",
  "Current Mount",
  "Auto Claim",
  "Testing Decision",
  "Authority",
] as const);

type TodoProjectionColumn = (typeof TODO_PROJECTION_COLUMNS)[number];
type TodoProjectionRow = Readonly<Record<TodoProjectionColumn, string>>;
const ESCAPED_TEXT_COLUMNS = new Set<TodoProjectionColumn>([
  "Summary",
  "Intake Rationale",
  "Dependency / Trigger",
  "Testing Decision",
]);

const TODO_PROJECTION_HEADER =
  `| ${TODO_PROJECTION_COLUMNS.join(" | ")} |`;
const TODO_PROJECTION_DIVIDER =
  `| ${TODO_PROJECTION_COLUMNS.map(() => "---").join(" | ")} |`;

const PREFIX_LINES = Object.freeze([
  "# Global TODO Board",
  "",
  "This file is a deterministic projection. Durable TODO authority lives under `todo/items/`; do not edit this file by hand.",
  "",
  "## Global TODO",
  "",
  TODO_PROJECTION_HEADER,
  TODO_PROJECTION_DIVIDER,
] as const);

function authorityLinks(
  authorityRefs: Readonly<
    TodoCollectionSnapshot["items"][number]["intake"]["authorityRefs"]
  >,
): string {
  return authorityRefs.map((reference) => (
    `[${reference.role}](${encodeMarkdownLinkDestination(reference.memberRef)})`
  )).join(" ");
}

function encodeMarkdownLinkComponent(value: string): string {
  return encodeURIComponent(value).replace(/[!'()*]/gu, (character) => (
    `%${character.charCodeAt(0).toString(16).toUpperCase()}`
  ));
}

function encodeMarkdownLinkDestination(value: string): string {
  return value.split("/").map(encodeMarkdownLinkComponent).join("/");
}

function rowFor(
  item: TodoCollectionSnapshot["items"][number],
): TodoProjectionRow {
  return {
    ID: item.todoId,
    Status: item.state.status,
    "Demand Type": item.intake.demandType,
    Priority: item.intake.priority,
    "Origin Window": item.intake.originWindowId,
    "Controller Window": item.intake.controllerWindowId,
    Summary: item.intake.summary,
    "Intake Rationale": item.intake.intakeRationale,
    "Dependency / Trigger": item.intake.readiness.status === "parked"
      ? item.intake.readiness.trigger
      : "none",
    "Current Mount": item.state.mount?.stateRootRef ?? "none",
    "Auto Claim": item.intake.autoClaim ? "yes" : "no",
    "Testing Decision": `${item.intake.testingDecision.mode}: ${item.intake.testingDecision.summary}`,
    Authority: authorityLinks(item.intake.authorityRefs),
  };
}

/** Markdown 是单向投影；只转义显示保留符，不提供反向领域解析。 */
function encodeMarkdownCell(value: string): string {
  return value
    .replace(/[\u061c\u200e\u200f\u202a-\u202e\u2066-\u2069]/gu, (character) => (
      `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`
    ))
    .replaceAll("&", "&amp;")
    .replaceAll("\\", "&#92;")
    .replaceAll("|", "&#124;")
    .replaceAll("`", "&#96;")
    .replaceAll("*", "&#42;")
    .replaceAll("_", "&#95;")
    .replaceAll("~", "&#126;")
    .replaceAll("[", "&#91;")
    .replaceAll("]", "&#93;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replace(/\r\n?|\n/gu, "<br>");
}

function renderProjectionRow(row: TodoProjectionRow): string {
  return `| ${TODO_PROJECTION_COLUMNS.map((column) => (
    ESCAPED_TEXT_COLUMNS.has(column)
      ? encodeMarkdownCell(row[column])
      : row[column]
  )).join(" | ")} |`;
}

/** 从完整 JSON 权威集合纯渲染 Markdown 看板投影。 */
export function renderTodoBoardProjection(
  items: unknown,
): Readonly<TodoBoardProjection> {
  const collection = createTodoCollectionSnapshot(items);
  const rows = collection.items
    .filter((item) => isTodoCollectionStatusActive(item.state.status))
    .map((item) => renderProjectionRow(rowFor(item)));
  const content = `${PREFIX_LINES.join("\n")}\n${
    rows.length === 0 ? "" : `${rows.join("\n")}\n`
  }`;
  return Object.freeze({
    artifactKind: TODO_BOARD_PROJECTION_KIND,
    schemaVersion: TODO_BOARD_PROJECTION_VERSION,
    resourcePath: TODO_BOARD_PROJECTION_REF,
    basisDigest: collection.collectionDigest,
    sourceDigest: computeSha256Digest(encodeUtf8(content, "$projection")),
    rowCount: rows.length,
    content,
  });
}
