import { computeSha256Digest, type Sha256Digest } from "../../foundation/crypto/sha256.js";
import { encodeUtf8 } from "../../foundation/text/utf8.js";
import {
  createTodoCollectionSnapshot,
  type TodoCollectionSnapshot,
} from "./todo-collection.js";
import { TODO_BOARD_PROJECTION_REF } from "./todo-paths.js";

/**
 * Wakeflow Governance / TODO：JSON authority collection 的 Markdown projection。
 *
 * Projection 只消费已验证 intake/state snapshot；archived item 不展示。文件内容携带
 * collection basis digest，缺失或损坏时可以重建，绝不能被 claim/archive 反向读取。
 */

export const TODO_BOARD_PROJECTION_KIND =
  "wakeflow-todo-board-projection" as const;
export const TODO_BOARD_PROJECTION_VERSION = 1 as const;

export interface TodoBoardProjection {
  readonly artifactKind: typeof TODO_BOARD_PROJECTION_KIND;
  readonly schemaVersion: typeof TODO_BOARD_PROJECTION_VERSION;
  readonly resourcePath: typeof TODO_BOARD_PROJECTION_REF;
  readonly basisDigest: Sha256Digest;
  readonly sourceDigest: Sha256Digest;
  readonly rowCount: number;
  readonly content: string;
}

const TODO_PROJECTION_COLUMNS = Object.freeze([
  "ID",
  "Status",
  "Type",
  "Priority",
  "Owner",
  "Item / Goal",
  "Affects Retest / Dispatch",
  "Dependency / Trigger",
  "Recommended Window",
  "Current Mount",
  "Auto Claim",
  "Testing Decision",
  "Documents",
] as const);

type TodoProjectionColumn = (typeof TODO_PROJECTION_COLUMNS)[number];
type TodoProjectionRow = Readonly<Record<TodoProjectionColumn, string>>;

const TODO_PROJECTION_HEADER =
  `| ${TODO_PROJECTION_COLUMNS.join(" | ")} |`;
const TODO_PROJECTION_DIVIDER =
  `| ${TODO_PROJECTION_COLUMNS.map(() => "---").join(" | ")} |`;

const PREFIX_LINES = Object.freeze([
  "# Global TODO Board",
  "",
  "This file is a deterministic projection. Durable TODO authority lives under `todo/items/`; do not edit this file by hand.",
  "",
  "## Global TODO",
  "",
  TODO_PROJECTION_HEADER,
  TODO_PROJECTION_DIVIDER,
] as const);

function documentLinks(
  documents: Readonly<TodoCollectionSnapshot["items"][number]["intake"]["documents"]>,
): string {
  return documents.map((document) => (
    `[${document.label}](${document.ref}${
      document.anchor === null ? "" : `#${document.anchor}`
    })`
  )).join(" ");
}

function rowFor(
  item: TodoCollectionSnapshot["items"][number],
): TodoProjectionRow {
  return {
    ID: item.todoId,
    Status: item.state.status,
    Type: item.intake.type,
    Priority: item.intake.priority,
    Owner: item.intake.ownerWindowId,
    "Item / Goal": item.intake.goal,
    "Affects Retest / Dispatch": item.intake.affectsRetestOrDispatch ? "yes" : "no",
    "Dependency / Trigger": item.intake.dependency ?? "none",
    "Recommended Window": item.intake.recommendedWindowId,
    "Current Mount": item.state.mount?.stateRootRef ?? "none",
    "Auto Claim": item.intake.autoClaim ? "yes" : "no",
    "Testing Decision": `${item.intake.testingDecision.mode}: ${item.intake.testingDecision.summary}`,
    Documents: documentLinks(item.intake.documents),
  };
}

/** Markdown 是单向投影；只转义显示保留符，不提供反向领域解析。 */
function encodeMarkdownCell(value: string): string {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("|", "\\|")
    .replace(/\r\n?|\n/gu, "<br>");
}

function renderProjectionRow(row: TodoProjectionRow): string {
  return `| ${TODO_PROJECTION_COLUMNS.map((column) => (
    encodeMarkdownCell(row[column])
  )).join(" | ")} |`;
}

/** 从完整 JSON authority collection 纯渲染 Markdown board projection。 */
export function renderTodoBoardProjection(
  items: unknown,
): Readonly<TodoBoardProjection> {
  const collection = createTodoCollectionSnapshot(items);
  const rows = collection.items
    .filter((item) => item.status !== "archived")
    .map((item) => renderProjectionRow(rowFor(item)));
  const content = `${PREFIX_LINES.join("\n")}\n${
    rows.length === 0 ? "" : `${rows.join("\n")}\n`
  }`;
  return Object.freeze({
    artifactKind: TODO_BOARD_PROJECTION_KIND,
    schemaVersion: TODO_BOARD_PROJECTION_VERSION,
    resourcePath: TODO_BOARD_PROJECTION_REF,
    basisDigest: collection.collectionDigest,
    sourceDigest: computeSha256Digest(encodeUtf8(content, "$projection")),
    rowCount: rows.length,
    content,
  });
}
